version: "2"
services:
  frontend:
    image: "node:current"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "8080:8080"
    command: "sh run.sh"
  backend:
    build:
      context: backend
      args:
       - DOCKER_UID=1000
       - DOCKER_GID=1000
    volumes:
      - ./backend:/workspace/
    ports:
     - 8000:8000
    command: "uvicorn server:app --host 0.0.0.0 --reload"